# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ITetP6Xb_nAeFEOZVzkcKii1kWb-FSyF
"""

import pandas as pd
Hisobot=pd.DataFrame({
    'Isim':[' Durbek '   ],
    'Famailiya ':['Xalilov '   ],
    'Kafedirasi':["Axborot texnlogiyalari"],
    'Fakulteti':["Kompyuter injineringi va sun'iy intellekt"  ],
     'Fani ': ["sun'iy intelekt"],
    "Mashg'ulot turi":["Ma'ruza"],
    'Telefon raqami':[  '91 681 17 30'   ],
    'Manzil':["Farg'ona Shahar"],
    'Oliy talim':['TATUFF'],
})
print(Hisobot)

Hisobot.to_excel('Hisobot.xlxs', index=False, sheet_name='sheet1')